/** プロジェクト/投稿設定のライセンス選択肢（Autocomplete の候補） */
export const LICENSE_OPTIONS = [
  "MIT",
  "MIT-0",
  "Apache-2.0",
  "GPL-2.0",
  "GPL-3.0",
  "LGPL-2.1",
  "LGPL-3.0",
  "GPL-2.0 or later",
  "GPL-3.0 or later",
  "LGPL-2.1 or later",
  "LGPL-3.0 or later",
  "MPL-2.0",
  "AGPL-3.0",
  "AGPL-3.0 or later",
  "All Rights Reserved",
  "CC0-1.0",
  "CC-BY-4.0",
  "CC-BY-SA-4.0",
  "CC-BY-NC-4.0",
  "CC-BY-ND-4.0",
  "WTFPL",
  "Unlicense",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "0BSD",
  "Proprietary",
] as const;
