import * as schema from "@/db/schema";

export const SCHEMA_TABLES: Record<string, any> = {
  users: schema.users,
  user_profiles: schema.userProfiles,
  user_settings: schema.userSettings,
  account: schema.accounts,
  session: schema.sessions,
  verificationToken: schema.verificationTokens,
  api_keys: schema.apiKeys,
  projects: schema.projects,
  categories: schema.categories,
  project_categories: schema.projectCategories,
  versions: schema.versions,
  version_loaders: schema.versionLoaders,
  version_mc_versions: schema.versionMcVersions,
  project_tags: schema.projectTags,
  project_dependencies: schema.projectDependencies,
  project_members: schema.projectMembers,
  project_favorites: schema.projectFavorites,
  project_media: schema.projectMedia,
  collections: schema.collections,
  collection_items: schema.collectionItems,
  reports: schema.reports,
  ideas: schema.ideas,
  idea_likes: schema.ideaLikes,
  idea_comments: schema.ideaComments,
  version_ideas: schema.versionIdeas,
  tags: schema.tags,
  platforms: schema.platforms,
  authenticator: schema.authenticators,
  rate_limits: schema.rateLimits,
  user_follows: schema.userFollows,
  collection_follows: schema.collectionFollows,
  project_comments: schema.projectComments,
  password_reset_tokens: schema.passwordResetTokens,
  project_subscriptions: schema.projectSubscriptions,
  developer_subscriptions: schema.developerSubscriptions,
  notifications: schema.notifications,
  scan_appeals: schema.scanAppeals,
};

export const TABLE_RESTORE_ORDER = [
  "users",
  "tags",
  "platforms",
  "rate_limits",
  "user_profiles",
  "user_settings",
  "account",
  "session",
  "verificationToken",
  "api_keys",
  "projects",
  "categories",
  "project_categories",
  "versions",
  "version_loaders",
  "version_mc_versions",
  "project_tags",
  "project_dependencies",
  "project_members",
  "project_favorites",
  "project_media",
  "collections",
  "collection_items",
  "reports",
  "ideas",
  "idea_likes",
  "idea_comments",
  "version_ideas",
  "authenticator",
  "user_follows",
  "collection_follows",
  "project_comments",
  "password_reset_tokens",
  "project_subscriptions",
  "developer_subscriptions",
  "notifications",
  "scan_appeals",
];

export const TABLE_PRIMARY_KEYS: Record<string, string[]> = {
  users: ["id"],
  user_profiles: ["userId"],
  user_settings: ["userId"],
  account: ["provider", "providerAccountId"],
  session: ["sessionToken"],
  verificationToken: ["identifier", "token"],
  api_keys: ["id"],
  projects: ["id"],
  categories: ["id"],
  project_categories: ["projectId", "categoryId"],
  versions: ["id"],
  version_loaders: ["versionId", "loader"],
  version_mc_versions: ["versionId", "mcVersion"],
  project_tags: ["projectId", "tag"],
  project_dependencies: ["id"],
  project_members: ["projectId", "userId"],
  project_favorites: ["projectId", "userId"],
  project_media: ["id"],
  collections: ["id"],
  collection_items: ["collectionId", "projectId"],
  reports: ["id"],
  ideas: ["id"],
  idea_likes: ["ideaId", "userId"],
  idea_comments: ["id"],
  version_ideas: ["versionId", "ideaId"],
  tags: ["id"],
  platforms: ["id"],
  authenticator: ["userId", "credentialID"],
  rate_limits: ["id"],
  user_follows: ["followerId", "followingId"],
  collection_follows: ["userId", "collectionId"],
  project_comments: ["id"],
  password_reset_tokens: ["id"],
  project_subscriptions: ["userId", "projectId"],
  developer_subscriptions: ["subscriberId", "developerId"],
  notifications: ["id"],
  scan_appeals: ["id"],
};
